# Generated by Django 3.1.5 on 2021-03-09 13:19

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionaireDData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='full name')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default=1, max_length=10)),
                ('country', django_countries.fields.CountryField(default=1, max_length=2)),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('age', models.CharField(choices=[('15-19', '15-19'), ('20-24', '20-24'), ('25-29', '25-29'), ('30-34', '30-34'), ('35-39', '35-39'), ('40-44', '40-44'), ('45-49', '45-49'), ('50-54', '50-54'), ('55-59', '55-59'), ('60-64', '60-64'), ('65-69', '65-69'), ('70-74', '70-74'), ('75-79', '75-79'), ('85-89', '85-89'), ('95-99', '95-99')], default=1, max_length=10)),
                ('question_1', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 1')),
                ('question_2', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 2')),
                ('question_3', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 3')),
                ('question_4', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 4')),
                ('question_5', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 5')),
                ('question_6', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 6')),
                ('question_7', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 7')),
                ('question_8', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 8')),
                ('question_9', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 9')),
                ('question_10', models.CharField(choices=[('No', ' No '), ('Yes', 'Yes'), ('Not sure', 'Not sure')], default=1, max_length=400, verbose_name='question 10')),
                ('question_11', models.CharField(choices=[('No', ' No '), ('Yes', 'Yes'), ('Not sure', 'Not sure')], default=1, max_length=400, verbose_name='question 11')),
                ('question_12', models.CharField(choices=[('No', ' No '), ('Yes', 'Yes'), ('Not sure', 'Not sure')], default=1, max_length=400, verbose_name='question 12')),
                ('question_13', models.CharField(choices=[('No', ' No '), ('Yes', 'Yes'), ('Not sure', 'Not sure')], default=1, max_length=400, verbose_name='question 13')),
                ('question_14', models.CharField(choices=[('No', ' No '), ('Yes', 'Yes'), ('Not sure', 'Not sure')], default=1, max_length=400, verbose_name='question 14')),
                ('question_15', models.CharField(choices=[('No', ' No '), ('Yes', 'Yes'), ('Not sure', 'Not sure')], default=1, max_length=400, verbose_name='question 15')),
                ('question_16', models.CharField(choices=[('No', ' No '), ('Yes', 'Yes'), ('Not sure', 'Not sure')], default=1, max_length=400, verbose_name='question 16')),
                ('question_17', models.CharField(choices=[('No', ' No '), ('Yes', 'Yes'), ('Not sure', 'Not sure')], default=1, max_length=400, verbose_name='question 17')),
                ('question_18', models.CharField(choices=[('No', ' No '), ('Yes', 'Yes'), ('Not sure', 'Not sure')], default=1, max_length=400, verbose_name='question 18')),
                ('question_19', models.CharField(choices=[('No', ' No '), ('Yes', 'Yes'), ('Not sure', 'Not sure')], default=1, max_length=400, verbose_name='question 19')),
                ('question_20', models.CharField(choices=[('Sign Language', 'Sign Language'), ('Easy Read or Plain Language', 'Easy Read or Plain Language'), ('Audio formats', 'audio formats'), ('Multiple languages', 'multiple languages'), ('Websites are accessible for screen reader users ', 'Websites are accessible for screen reader users '), ('Captioning services', 'Captioning services'), ('Other (please specify)', 'Other (please specify)'), ('No information has been provided in any format', 'No information has been provided in any format')], default=1, max_length=400, verbose_name='question 20')),
                ('question_21', models.CharField(choices=[('Not at all', 'Not at all'), ('Little support was given', 'Little support was given'), ('Adequate support was given', 'Adequate support was given')], default=1, max_length=400, verbose_name='question 21')),
                ('question_22', models.CharField(choices=[('Not at all', 'Not at all'), ('Sometimes', 'Sometimes'), ('All the time', 'All the time')], default=1, max_length=400, verbose_name='question 22')),
                ('question_23', models.CharField(choices=[('True', True), ('False', False)], default=1, max_length=400, verbose_name='question 23')),
            ],
            options={
                'verbose_name': 'Descriptive Data Questionaire',
                'verbose_name_plural': 'Descriptive Data Questionaires',
            },
        ),
        migrations.CreateModel(
            name='QuestionaireStakeHolders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=50, verbose_name='full name')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default=1, max_length=10)),
                ('country', django_countries.fields.CountryField(default=1, max_length=2)),
                ('age', models.CharField(choices=[('15-19', '15-19'), ('20-24', '20-24'), ('25-29', '25-29'), ('30-34', '30-34'), ('35-39', '35-39'), ('40-44', '40-44'), ('45-49', '45-49'), ('50-54', '50-54'), ('55-59', '55-59'), ('60-64', '60-64'), ('65-69', '65-69'), ('70-74', '70-74'), ('75-79', '75-79'), ('85-89', '85-89'), ('95-99', '95-99')], default=1, max_length=10)),
                ('stakeholder_class', models.CharField(choices=[('Government', 'Government'), ('Inter governmental organization', 'Inter governmental organization'), ('Human rights organization', 'Human rights organization'), ('Organization of persons with disability', 'Organization of persons with disability'), ('Family member of person with disabilities', 'Family member of person with disabilities'), ('Public healthcare organization', 'Public healthcare organization'), ('Private healthcare organization', 'Private healthcare organization'), ('Other (Specify)', 'Other (Specify)')], max_length=300)),
                ('question_1', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 1')),
                ('question_2', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 2')),
                ('question_3', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 3')),
                ('question_4', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 4')),
                ('question_5', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 5')),
                ('question_6', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 6')),
                ('question_7', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 7')),
                ('question_8', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 8')),
                ('question_9', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 9')),
                ('question_10', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 10')),
                ('question_11', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 11')),
                ('question_12', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 12')),
                ('question_13', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 13')),
                ('question_14', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 14')),
                ('question_15', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 15')),
                ('question_16', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 16')),
                ('question_17', models.CharField(choices=[('Strongly disagree', 'Strongly disagree '), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default=1, max_length=400, verbose_name='question 17')),
                ('question_18', models.CharField(choices=[('No', ' No '), ('Yes', 'Yes'), ('Not sure', 'Not sure')], default=1, max_length=400, verbose_name='question 18')),
                ('question_19', models.CharField(choices=[('No', ' No '), ('Yes', 'Yes'), ('Not sure', 'Not sure')], default=1, max_length=400, verbose_name='question 19')),
                ('question_20', models.CharField(choices=[('No', ' No '), ('Yes', 'Yes'), ('Not sure', 'Not sure')], default=1, max_length=400, verbose_name='question 20')),
                ('question_21', models.CharField(choices=[('No', ' No '), ('Yes', 'Yes'), ('Not sure', 'Not sure')], default=1, max_length=400, verbose_name='question 21')),
                ('question_22', models.CharField(choices=[('No', ' No '), ('Yes', 'Yes'), ('Not sure', 'Not sure')], default=1, max_length=400, verbose_name='question 22')),
                ('question_23', models.CharField(choices=[('No', ' No '), ('Yes', 'Yes'), ('Not sure', 'Not sure')], default=1, max_length=400, verbose_name='question 23')),
                ('question_24', models.CharField(choices=[('No', ' No '), ('Yes', 'Yes'), ('Not sure', 'Not sure')], default=1, max_length=400, verbose_name='question 24')),
                ('question_25', models.CharField(choices=[('No', ' No '), ('Yes', 'Yes'), ('Not sure', 'Not sure')], default=1, max_length=400, verbose_name='question 25')),
                ('question_26', models.CharField(choices=[('Sign Language', 'Sign Language'), ('Easy Read or Plain Language', 'Easy Read or Plain Language'), ('Audio formats', 'audio formats'), ('Multiple languages', 'multiple languages'), ('Websites are accessible for screen reader users ', 'Websites are accessible for screen reader users '), ('Captioning services', 'Captioning services'), ('Other (please specify)', 'Other (please specify)'), ('No information has been provided in any format', 'No information has been provided in any format')], default=1, max_length=400, verbose_name='question 26')),
                ('question_27', models.CharField(choices=[('Not at all', 'Not at all'), ('Little support was given', 'Little support was given'), ('Adequate support was given', 'Adequate support was given')], default=1, max_length=400, verbose_name='question 27')),
                ('question_28', models.CharField(choices=[('True', True), ('False', False)], default=1, max_length=400, verbose_name='question 28')),
            ],
            options={
                'verbose_name': 'StakeHolders Questionaire',
                'verbose_name_plural': 'StakeHolders Questionaires',
            },
        ),
    ]
